language: generic

sudo: required
services:
 - docker

before_install:
 - docker build -t vikas/travis -f Dockerfile.dev .
 
script:
 - docker run -e CI=true vikas/travis npm run test


deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "dockerApp"
 env: "Dockerapp-env"
 bucket_name: "elasticbeanstalk-us-east-2-619038546570" 
 bucket_path: "dockerApp"

 on:
   branch: master

 access_key_id:
   secure: "$AWS_ACCESS_ID"
 
 secret_access_key:
   secure: "$AWS_SECRET_KEY"


# http://dockerapp-env.t2k2prwxhx.us-east-2.elasticbeanstalk.com/





